Update build-ami.yml

diff --git a/.github/workflows/build-ami.yml b/.github/workflows/build-ami.yml
--- a/.github/workflows/build-ami.yml
+++ b/.github/workflows/build-ami.yml
@@ -99,14 +99,11 @@ jobs:
            fi
     
     
-          # launch_template_name=$(aws ec2 describe-launch-templates --query 'LaunchTemplates[?contains(LaunchTemplateName, `launch_template`)].LaunchTemplateName' --output text)
-          # if [ -z "$launch_template_name" ]; then
-          #   echo "Launch template not found"
-          #   exit 1
-          # fi
-
-
-          launch_template_name=launch_template_test
+          launch_template_name=$(aws ec2 describe-launch-templates --query 'LaunchTemplates[?contains(LaunchTemplateName, `launch_template`)].LaunchTemplateName' --output text)
+          if [ -z "$launch_template_name" ]; then
+            echo "Launch template not found"
+            exit 1
+          fi
       
           echo "Using launch template: $launch_template_name"
       
@@ -121,7 +118,7 @@ jobs:
           echo "Using Auto Scaling Group: $asg_name"
       
           # Create a new version of the Launch Template with the latest AMI
-          new_version=$(aws ec2 create-launch-template-version --launch-template-name "$launch_template_name" --version-description "New version" --launch-template-data "{\"ImageId\":\"$latest_ami_id\"}")
+          new_version=$(aws ec2 create-launch-template-version --launch-template-name "$launch_template_name" --version-description "New version" --launch-template-data "{\"ImageId\":\"$latest_ami_id\", \"InstanceType\":\"t2.micro\"}")
       
           # Extract the new version number
           new_version_number=$(echo $new_version | jq -r '.LaunchTemplateVersion.VersionNumber')
